KEY_CTRL_Q:   [Application, Quit]
KEY_RIGHT:    [Application, Forward]
KEY_LEFT:     [Application, Backward]
KEY_SRIGHT:   [Application, ForwardMeasure]
KEY_SLEFT:    [Application, BackwardMeasure]
KEY_CTRL_W:   [Application, Rewind]
KEY_UP:       [Application, Up]
KEY_DOWN:     [Application, Down]
KEY_CTRL_U:   [Application, PageUp]
KEY_CTRL_D:   [Application, PageDown]
'u':          [Application, Undo]
KEY_CTRL_R:   [Application, Redo]
KEY_CTRL_I:   [Application, Tie]
127:          [Application, Untie]
KEY_DC:       [Application, Remove]
' ':          [Application, Rest]
'>':          [Application, OctaveUp]
'<':          [Application, OctaveDown]
164:          [Application, QuantizeUp]
165:          [Application, QuantizeDown]
'4':          [Application, Quantize4]
'8':          [Application, Quantize8]
'6':          [Application, Quantize16]
'3':          [Application, Quantize32]
KEY_CTRL_P:   [Application, TogglePlay]
'r':          [Application, ToggleRec]
KEY_CTRL_C:   [Application, ToggleChordInput]
'z':          [Application, Note, -3]
's':          [Application, Note, -2]
'x':          [Application, Note, -1]
'c':          [Application, Note,  0]
'f':          [Application, Note,  1]
'v':          [Application, Note,  2]
'g':          [Application, Note,  3]
'b':          [Application, Note,  4]
'n':          [Application, Note,  5]
'j':          [Application, Note,  6]
'm':          [Application, Note,  7]
'k':          [Application, Note,  8]
',':          [Application, Note,  9]
'l':          [Application, Note, 10]
'.':          [Application, Note, 11]
'/':          [Application, Note, 12]
'Z':          [Application, Note,  9]
'S':          [Application, Note, 10]
'X':          [Application, Note, 11]
'C':          [Application, Note, 12]
'F':          [Application, Note, 13]
'V':          [Application, Note, 14]
'G':          [Application, Note, 15]
'B':          [Application, Note, 16]
'N':          [Application, Note, 17]
'J':          [Application, Note, 18]
'M':          [Application, Note, 19]
'K':          [Application, Note, 20]
KEY_CTRL_J:   [Application, CommitNotes]
':':          [Controller, Command]
'+':          [Controller, ZoomIn]
'-':          [Controller, ZoomOut]
'=':          [Controller, ZoomReset]
KEY_CTRL_T:   [Controller, SwitchTrack]
