class Context
	convert_table = {
		'High Q'           => 27,
		'Slap'             => 28,
		'Scratch Push'     => 29,
		'Scratch Pull'     => 30,
		'Sticks'           => 31,
		'Square Click'     => 32,
		'Metronome Click'  => 33,
		'Metronome Bell'   => 34,
		'Kick Drum2'       => 35,
		'Bass Drum1'       => 36,
		'Side Stick'       => 37,
		'Snare Drum1'      => 38,
		'Hand Clap'        => 39,
		'Snare Drum2'      => 40,
		'Low Tom2'         => 41,
		'Closed Hi-hat'    => 42,
		'Low Tom1'         => 43,
		'Pedal Hi-hat'     => 44,
		'Mid Tom2'         => 45,
		'Open Hi-hat'      => 46,
		'Mid Tom1'         => 47,
		'Hi-Mid Tom'       => 48,
		'Crash Cymbal1'    => 49,
		'High Tom1'        => 50,
		'Ride Cymbal1'     => 51,
		'Chinese Cymbal'   => 52,
		'Ride Bell'        => 53,
		'Tambourine'       => 54,
		'Splash Cymbal'    => 55,
		'Cowbell'          => 56,
		'Crash Cymbal2'    => 57,
		'Vibra-Slap'       => 58,
		'Ride Cymbal2'     => 59,
		'Hi Bongo'         => 60,
		'Low Bongo'        => 61,
		'Mute High Conga'  => 62,
		'Open High Conga'  => 63,
		'Low Conga'        => 64,
		'High Timbale'     => 65,
		'Low Timbale'      => 66,
		'High Agogo'       => 67,
		'Low Agogo'        => 68,
		'Cabasa'           => 69,
		'Maracas'          => 70,
		'Short Hi Whistle' => 71,
		'Long Whistle'     => 72,
		'Short Guiro'      => 73,
		'Long Guiro'       => 74,
		'Claves'           => 75,
		'High Wood Block'  => 76,
		'Low Wood Block'   => 77,
		'Mute Cuica'       => 78,
		'Open Cuica'       => 79,
		'Mute Triangle'    => 80,
		'Open Triangle'    => 81,
		'Shaker'           => 82,
		'Jingle Bell'      => 83,
		'Bell Tree'        => 84,
		'Castanets'        => 85,
		'Mute Surdo'       => 86,
		'Open Surdo'       => 87
	}

	@@convert_table.merge!(convert_table)
end

